/**
 * Renders the kasas config.toml from the app's managed settings. Regenerated
 * whenever settings change — hand edits to this file are overwritten.
 *
 * Config ownership is SPLIT: this file owns the boot-only / file-managed keys
 * (server, database, secrets, dashboard token, and the update safety pins).
 * The sync/log/plugins/events/etc. blocks emitted here are only first-boot
 * SEED defaults — at runtime they are edited via the kasas API (Settings →
 * Kasas), whose stored overrides win over this file. So changing them in the
 * app no longer rewrites this file.
 */

import type { KasasSettings } from '../../shared/ipc';
import { kasasDbPath, kasasSecretsPath } from './paths';

function tomlString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

export function renderConfigToml(settings: KasasSettings, token: string): string {
  return [
    '# Generated by sillview — changes made here are overwritten when you edit',
    '# settings in the app. Configure data sources via the kasas web UI at',
    `# http://127.0.0.1:${settings.port} until in-app source setup lands.`,
    '',
    '[server]',
    `addr = "127.0.0.1:${settings.port}"`,
    '',
    '[log]',
    `level = "${settings.logLevel}"`,
    'format = "json"',
    '',
    '[database]',
    'driver = "sqlite"',
    `path = "${tomlString(kasasDbPath())}"`,
    '',
    '[secrets]',
    `file = "${tomlString(kasasSecretsPath())}"`,
    '',
    '[sync]',
    `enabled = ${settings.sync.enabled}`,
    `interval = "${settings.sync.interval}"`,
    `run_on_start = ${settings.sync.runOnStart}`,
    `lookback_days = ${settings.sync.lookbackDays}`,
    '',
    '[dashboard]',
    'enabled = true',
    `token = "${tomlString(token)}"`,
    '',
    '[update]',
    '# A bundled binary must never replace itself — sillview ships updates.',
    'check = false',
    'allow_apply = false',
    '',
  ].join('\n');
}
